export default new function(){
    
    /** Пользователь */

    this.RECEIVE_PATIENT_DATA = 'RECEIVE_PATIENT_DATA';
    this.REQUEST_UPDATE_PATIENT = 'REQUEST_UPDATE_PATIENT';

    this.ADD_FRAME_MEDIC_INFO = 'ADD_FRAME_MEDIC_INFO';
    this.DELETE_LAST_FRAME = 'DELETE_LAST_FRAME';
    
    // медика запрос
    this.REQUEST_MEDIC = 'REQUEST_MEDIC';
    this.RESPONSE_MEDIC_SUCCESS = 'RESPONSE_MEDIC_SUCCESS';
    this.RESPONSE_MEDIC_FAILURE = 'RESPONSE_MEDIC_FAILURE';

    // клиники запрос
    this.REQUEST_CLINIC = 'REQUEST_CLINIC';
    this.RESPONSE_CLINIC_SUCCESS = 'RESPONSE_CLINIC_SUCCESS';
    this.RESPONSE_CLINIC_FAILURE = 'RESPONSE_CLINIC_FAILURE';

    // все клиники
    this.REQUEST_ALL_CLINICS = 'REQUEST_ALL_CLINICS';
    this.RESPONSE_ALL_CLINICS_SUCCESS = 'RESPONSE_ALL_CLINICS_SUCCESS';
    this.RESPONSE_ALL_CLINICS_FAILURE = 'RESPONSE_ALL_CLINICS_FAILURE';

    // медиков клиники запрос
    this.REQUEST_MEDICS_OF_CLINIC = 'REQUEST_MEDICS_OF_CLINIC';
    this.RESPONSE_MEDICS_OF_CLINIC_SUCCESS = 'RESPONSE_MEDICS_OF_CLINIC_SUCCESS';
    this.RESPONSE_MEDICS_OF_CLINIC_FAILURE = 'RESPONSE_MEDICS_OF_CLINIC_FAILURE';

    //
    this.REQUEST_RECEPTION = 'REQUEST_RECEPTION';
    this.RESPONSE_RECEPTION_SUCCESS = 'RESPONSE_RECEPTION_SUCCESS';
    this.RESPONSE_RECEPTION_FAILURE = 'RESPONSE_RECEPTION_FAILURE';

    // 
    this.REQUEST_ALL_RECEPTIONS = 'REQUEST_ALL_RECEPTIONS';
    this.RESPONSE_ALL_RECEPTIONS_SUCCESS = 'RESPONSE_ALL_RECEPTIONS_SUCCESS';
    this.RESPONSE_ALL_RECEPTIONS_FAILURE = 'RESPONSE_ALL_RECEPTIONS_FAILURE';
    
    // словарь специальностей
    this.REQUEST_SPECIALITIES = 'REQUEST_SPECIALITIES';
    this.RESPONSE_SPECIALITIES_SUCCESS = 'RESPONSE_SPECIALITIES_SUCCESS';
    this.RESPONSE_SPECIALITIES_FAILURE = 'RESPONSE_SPECIALITIES_FAILURE';
    
    this.RECEIVE_MEDIC = 'RECEIVE_MEDIC';
    this.RECEIVE_CLINIC = 'RECEIVE_CLINIC';
    
    this.UPDATE_LANGUAGE_SETTINGS = 'UPDATE_LANGUAGE_SETTINGS';
    
    this.ATTACHMENT_CHOSEN_CLINIC_ID = 'ATTACHMENT_CHOSEN_CLINIC_ID';
    this.PUT_ATTACHMENT_FORM_DATA = 'PUT_ATTACHMENT_FORM_DATA';
    
    
    this.PUT_INSURANCE_DATA = 'PUT_INSURANCE_DATA';
    this.PUT_PASSPORT_DATA = 'PUT_PASSPORT_DATA';
    this.PUT_CONTACTS_DATA = 'PUT_CONTACTS_DATA';
    this.PUT_SETTINGS_DATA = 'PUT_SETTINGS_DATA';
    
    this.RESET_MEETING_FORM = 'RESET_MEETING_FORM';

    
    this.REQUEST_REGIONS = 'REQUEST_REGIONS';
    this.RESPONSE_REGIONS_SUCCESS = 'RESPONSE_REGIONS_SUCCESS';
    
    
    this.REQUEST_INSURANCE_COMPANIES = 'REQUEST_INSURANCE_COMPANIES';
    this.RESPONSE_INSURANCE_COMPANIES_SUCCESS = 'RESPONSE_INSURANCE_COMPANIES_SUCCESS';

    this.ADD_INSURANCE_DATA_TO_ATTACHMENT_FORM = 'ADD_INSURANCE_DATA_TO_ATTACHMENT_FORM';
    this.ADD_PASSPORT_DATA_TO_ATTACHMENT_FORM = 'ADD_PASSPORT_DATA_TO_ATTACHMENT_FORM';
    this.ADD_CONTACTS_DATA_TO_ATTACHMENT_FORM = 'ADD_CONTACTS_DATA_TO_ATTACHMENT_FORM';
    
    this.PUT_MEDIC_ID_TO_MEETING_FORM = 'PUT_MEDIC_ID_TO_MEETING_FORM';
    this.MEETING_CHOSEN_MEDIC_ID = 'MEETING_CHOSEN_MEDIC_ID';
    
    this.PUT_PASSWORD_DATA = 'PUT_PASSWORD_DATA';
    this.REQUEST_PASSWORD_FORM = 'REQUEST_PASSWORD_FORM';
    
    this.CHANGED_FEEDBACK_MESSAGE = 'CHANGED_FEEDBACK_MESSAGE';
    
    this.PUT_MEETING_TYPE_TO_MEETING_FORM = 'PUT_MEETING_TYPE_TO_MEETING_FORM';
    this.PUT_RECEPTION_TO_MEETING_FORM = 'PUT_RECEPTION_TO_MEETING_FORM';


    this.REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
    this.RESPONSE_SCHEDULE = 'RESPONSE_SCHEDULE';
    this.REMOVE_SCHEDULES = 'REMOVE_SCHEDULES';
    this.RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';
    
   
    
    this.RESPONSE_PATIENT_SUCCESS = 'RESPONSE_PATIENT_SUCCESS';
    this.RESPONSE_PATIENT_ERRORS = 'RESPONSE_PATIENT_ERRORS';
    
    this.RESPONSE_PASSWORD_SUCCESS = 'RESPONSE_PASSWORD_SUCCESS';
    this.RESPONSE_PASSWORD_ERRORS = 'RESPONSE_PASSWORD_ERRORS';

};

